name: Pytest-GPU

on:
  pull_request_target

jobs:
  pytest-gpu:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
