name: Pytest-GPU
on:
  pull_request_target:
jobs:
  pytest-gpu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        id: tests
        run: |
          set -ex
          export PATH=/composer-python:$PATH

          export MCLI_KEY='${{ secrets.MCLI_KEY }}'

          echo $MCLI_KEY
